# Generated by Django 4.2 on 2023-04-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255, verbose_name='Название препятствия')),
                ('title', models.CharField(max_length=255, verbose_name='Название вершины')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10)),
                ('connect', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевал',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(max_length=10, null=True, verbose_name='Зима')),
                ('summer', models.CharField(max_length=10, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(max_length=10, null=True, verbose_name='Осень')),
                ('spring', models.CharField(max_length=10, null=True, verbose_name='Весна')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровень сложности',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
    ]
