# Generated by Django 4.2 on 2023-04-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_images_data_alter_images_pereval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='data',
            new_name='images',
        ),
    ]
