# Generated by Django 4.2 on 2023-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_rename_images_images_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
