# Generated by Django 4.2 on 2023-04-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
    ]
